version: '3.11'
services:

  organizations_app:
    container_name: organizations_app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: final
    command: ./docker_commands.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      organizations_db:
        condition: service_healthy
    networks:
      - local
      - global

  organizations_db:
    container_name: organizations_db
    image: postgres:17
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./organizations:/data/organizations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 20s
      retries: 5
    networks:
      - local

volumes:
  organizations_app:
    driver: local
  organizations_db:
    driver: local

networks:
  local:
    driver: bridge
    internal: true
  global:
    driver: bridge
    internal: false
